# Use an official Python runtime as a parent image
FROM python

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r main-requirements.txt
RUN pip install appdynamics
RUN pip install pyagent
COPY appdynamics.cfg /etc/appdynamics.cfg
# Make port 8080 available to the world outside this container
EXPOSE 8090

# Define environment variable
ENV NAME World

# Run app.py when the container launches
CMD pyagent run -c /etc/appdynamics.cfg -- flask run --host 0.0.0.0 --port 8090
#CMD ["python", "main.py"]
